title: NeFL
description: Project page for NeFL
theme: just-the-docs

url: https://honggkang.github.io/nefl3/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
